branches:
  only:
    - master

image: Visual Studio 2017
platform: Any CPU

environment:
  nodejs_version: 11

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - node --version

build_script:
  - npm run build

test: off